# Generated by Django 4.2.3 on 2025-08-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('txt', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(null=True, upload_to='pdfs/')),
                ('external_url', models.URLField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
