# Generated by Django 4.2.3 on 2025-09-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspace', '0004_info_user_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='info',
            name='pdf_file',
        ),
    ]
